### ISSUE TITLE
all topics

### ISSUE THREAD

**Issue by tylerjw** [ros/rosbag_snapshot#5]
It would be nice if there was an option to have it just track all topics like rosbag.

**Comment by Timple** [comment]
This would be really nice. Especially since this tool is typically used in error cases (assumption). Upfront it is hard to predict what data we need for debugging afterwards.

rosbag record [periodically calls](https://github.com/ros/ros_comm/blob/19b90c2c61e17a2f8a462df0e2ac9a777710bf01/tools/rosbag/src/recorder.cpp#L199) the master to get a list of topics. So I assume this is the way to go here as well.

And then for every new topic [these lines](https://github.com/ros/rosbag_snapshot/blob/ac239f07448e1e51fb2ea65b9f38db7614c87beb/rosbag_snapshot/src/snapshotter.cpp#L516-L522) have to be repeated I guess.

@DLu would this work or is there (much) more involved to dynamically add topics to the queues?

**Comment by tylerjw** [comment]
Some context:

Right now I'm just maintaining a yaml config file that maintains the list of topics for rosbag_snapshot.  At this point in the development of the project I'm working on, people keep adding/changing topics and I seem to always be behind what they've done with my yaml config for this and when something goes wrong we are missing data.  If this was more of a production system (and less of a prototype) then tuning what things we care about in the yaml is a really nice solution.

**Comment by Timple** [comment]
This is fixed now.

@DLu would you mind creating a new release for the buildfarm to roll out this feature? :slightly_smiling_face:

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/27275
https://github.com/ros/rosdistro/pull/27276
https://github.com/ros/rosdistro/pull/27277
